# Variables
### Python | OpenSCAD
coding_language: "Python"
### Blender | OpenSCAD
shape_engine: "Blender"

# Performance-related
paths: 3
path_max_iter: 3

# Task-specific definitions
output_format:
  - ""
